#ifndef QGLOBE_SCENE_GLOBAL_H
#define QGLOBE_SCENE_GLOBAL_H

#include <qglobal.h>

#ifdef QGLOBE_STATIC_LIBRARY
# define QGLOBE_SCENE_EXPORT Q_DECL_IMPORT
#else
# define QGLOBE_SCENE_EXPORT Q_DECL_EXPORT
#endif

#endif // QGLOBE_SCENE_GLOBAL_H
