# -----------------------------------------------------------
# This file is generated by the Qt Visual Studio Integration.
# -----------------------------------------------------------


#Header files
HEADERS += ./gds_ctrldialog.h \
    ./gds_servicetrayicon.h

#Source files
SOURCES += ./gds_ctrldialog.cpp \
    ./gds_servicetrayicon.cpp \
    ./main.cpp

#Forms
FORMS += ./gds_ctrldialog.ui
