#ifndef GDEM_TERRAINENGINE_GLOBAL_H
#define GDEM_TERRAINENGINE_GLOBAL_H

#include <qglobal.h>

#ifdef GDEM_STATIC_LIBRARY
# define GDEM_TERRAINENGINE_EXPORT Q_DECL_IMPORT
#else
# define GDEM_TERRAINENGINE_EXPORT Q_DECL_EXPORT
#endif

#endif // GDEM_TERRAINENGINE_GLOBAL_H
