#ifndef RENDER_GLOBAL_H
#define RENDER_GLOBAL_H

#include <qglobal.h>

#ifdef GDEM_STATIC_LIBRARY
#define RENDER_EXPORT Q_DECL_IMPORT
#else
#define RENDER_EXPORT Q_DECL_EXPORT
#endif

class GDemClient;
extern GDemClient* g_app;

typedef enum
{
	eGDM_RENDER_NITIFY_NONE = 0,
	GDM_RENDER_NITIFY_START_ANIMATION,
	GDM_RENDER_NITIFY_END_ANIMATION,
	GDM_RENDER_NITIFY_CAMERA_CHANGED
}EGDM_RENDER_NOTIFY_TYPE;
#endif // RENDER_GLOBAL_H
