# -----------------------------------------------------------
# This file is generated by the Qt Visual Studio Integration.
# -----------------------------------------------------------


#Header files
HEADERS += ./Types.h \
    ./Alloc.h \
    ./LzFind.h \
    ./LzHash.h \
    ./LzmaDec.h \
    ./LzmaEnc.h \
    ./LzmaLib.h

#Source files
SOURCES += ./Alloc.c \
    ./LzFind.c \
    ./LzmaDec.c \
    ./LzmaEnc.c \
    ./LzmaLib.c
