# -----------------------------------------------------------
# This file is generated by the Qt Visual Studio Integration.
# -----------------------------------------------------------


#Header files
HEADERS += ./GDSTestSuiteManager.h \
    ./mainwindow.h

#Source files
SOURCES += ./GDSTestSuiteManager.cpp \
    ./main.cpp \
    ./mainwindow.cpp

#Forms
FORMS += ./gdstestsuite.ui

#Resource file(s)
RESOURCES += ./gdstestsuite.qrc
