# -----------------------------------------------------------
# This file is generated by the Qt Visual Studio Integration.
# -----------------------------------------------------------


#Header files
HEADERS += ./QGlobeDSCoreInterface.h \
    ./QGlobeDSRequestProcess.h

#Source files
SOURCES += ./QGlobeDSCoreInterface.cpp \
    ./QGlobeDSRequestProcess.cpp
