# -----------------------------------------------------------
# This file is generated by the Qt Visual Studio Integration.
# -----------------------------------------------------------


#Header files
HEADERS += ./GDSBlockFileManager.h \
    ./GDSDatabaseInterface.h \
    ./GDSFileManager.h \
    ./GDSGeoNameDBManager.h

#Source files
SOURCES += ./GDSBlockFileManager.cpp \
    ./GDSDatabaseInterface.cpp \
    ./GDSFileManager.cpp \
    ./GDSGeoNameDBManager.cpp
