# -----------------------------------------------------------
# This file is generated by the Qt Visual Studio Integration.
# -----------------------------------------------------------


#Header files
HEADERS += ./GDSNetworkInterface.h \
    ./GDSTcpServer.h \
    ./GDSTcpThread.h

#Source files
SOURCES += ./GDSNetworkInterface.cpp \
    ./GDSTcpServer.cpp \
    ./GDSTcpThread.cpp
