#ifndef QGLOBE_LIBMAIN_GLOBAL_H
#define QGLOBE_LIBMAIN_GLOBAL_H

#include <qglobal.h>

#ifdef QGLOBE_STATIC_LIBRARY
# define QGLOBE_LIBMAIN_EXPORT Q_DECL_IMPORT
#else
# define QGLOBE_LIBMAIN_EXPORT Q_DECL_EXPORT
#endif

#define QGlobe_RENDER_APPLY_OFFSET_BODY

#endif // QGLOBE_LIBMAIN_GLOBAL_H
