# -----------------------------------------------------------
# This file is generated by the Qt Visual Studio Integration.
# -----------------------------------------------------------
# Header files
HEADERS += ./qglobeds_service_monitoring.h

# Source files
SOURCES += ./qglobeds_service_monitoring.cpp \
    ./main.cpp
