# -----------------------------------------------------------
# This file is generated by the Qt Visual Studio Integration.
# -----------------------------------------------------------


#Header files
HEADERS += ./common.h \
    ./datachannel.h \
    ./dataconfig.h \
    ./datasrv.h \
    ./gdem_datasrv_global.h \
    ./stable.h

#Source files
SOURCES += ./datachannel.cpp \
    ./datasrv.cpp \
    ./dataconfig.cpp \
    ./stable.h.cpp
