# -----------------------------------------------------------
# This file is generated by the Qt Visual Studio Integration.
# -----------------------------------------------------------


#Header files
HEADERS += ./kml_creator.h \
    ./kml_objects.h \
    ./kml_parser.h \
    ./kml_treeitem.h \
    ./kmlmanagerclient.h

#Source files
SOURCES += ./kml_creator.cpp \
    ./kml_objects.cpp \
    ./kml_parser.cpp \
    ./kml_treeitem.cpp \
    ./kmlmanagerclient.cpp
