# -----------------------------------------------------------
# This file is generated by the Qt Visual Studio Integration.
# -----------------------------------------------------------


#Header files
HEADERS += ./qglobeds_ctrldialog.h \
    ./qglobeds_servicetrayicon.h

#Source files
SOURCES += ./qglobeds_ctrldialog.cpp \
    ./qglobeds_servicetrayicon.cpp \
    ./main.cpp

#Forms
FORMS += ./qglobeds_ctrldialog.ui
