#ifndef GDEM_LIBMAIN_GLOBAL_H
#define GDEM_LIBMAIN_GLOBAL_H

#include <qglobal.h>

#ifdef GDEM_STATIC_LIBRARY
# define GDEM_LIBMAIN_EXPORT Q_DECL_IMPORT
#else
# define GDEM_LIBMAIN_EXPORT Q_DECL_EXPORT
#endif

#define GDM_RENDER_APPLY_OFFSET_BODY

#endif // GDEM_LIBMAIN_GLOBAL_H
