# -----------------------------------------------------------
# This file is generated by the Qt Visual Studio Integration.
# -----------------------------------------------------------


#Header files
HEADERS += ./GDSCoreInterface.h \
    ./GDSRequestProcess.h

#Source files
SOURCES += ./GDSCoreInterface.cpp \
    ./GDSRequestProcess.cpp
