# -----------------------------------------------------------
# This file is generated by the Qt Visual Studio Integration.
# -----------------------------------------------------------


#Header files
HEADERS += ./QGlobeDSNetworkInterface.h \
    ./QGlobeDSTcpServer.h \
    ./QGlobeDSTcpThread.h

#Source files
SOURCES += ./QGlobeDSNetworkInterface.cpp \
    ./QGlobeDSTcpServer.cpp \
    ./QGlobeDSTcpThread.cpp
