# -----------------------------------------------------------
# This file is generated by the Qt Visual Studio Integration.
# -----------------------------------------------------------


#Header files
HEADERS += ./GDSCommon.h \
    ./GDSCommonInterface.h \
    ./GDSConfigMgr.h \
    ./GDSDefine.h \
    ./GDSLog.h \
    ./GDSType.h

#Source files
SOURCES += ./GDSCommon.cpp \
    ./GDSCommonInterface.cpp \
    ./GDSConfigMgr.cpp \
    ./GDSLog.cpp
